#!/usr/bin/env python3
"""Generate thesis outline from chapter files — P1 deterministic extraction.

Parses markdown heading structure from all chapter files and produces
a hierarchical outline. No LLM involvement — pure markdown parsing.

Usage:
  python3 generate_thesis_outline.py --project-dir <dir>
  python3 generate_thesis_outline.py --project-dir <dir> --output outline.md
  python3 generate_thesis_outline.py --project-dir <dir> --format json
"""

import argparse
import json
import re
import sys
from pathlib import Path

HEADING_PATTERN = re.compile(r'^(#{1,6})\s+(.+)$', re.MULTILINE)

# Expected chapter order
CHAPTER_ORDER = [
    "abstract.md",
    "chapter-1-introduction.md",
    "chapter-2-literature-review.md",
    "chapter-3-methodology.md",
    "chapter-4-theological-argument.md",
    "chapter-4-results.md",
    "chapter-5-philosophical-argument.md",
    "chapter-5-discussion.md",
    "chapter-6-discussion.md",
    "chapter-6-conclusion.md",
    "chapter-7-conclusion.md",
]


def extract_outline(file_path: Path) -> list[dict]:
    """Extract heading structure from a markdown file."""
    content = file_path.read_text(encoding="utf-8")
    headings = []
    for match in HEADING_PATTERN.finditer(content):
        level = len(match.group(1))
        title = match.group(2).strip()
        headings.append({
            "level": level,
            "title": title,
            "indent": "  " * (level - 1),
        })
    return headings


def count_words(file_path: Path) -> int:
    """Count words in a markdown file (excluding code blocks)."""
    content = file_path.read_text(encoding="utf-8")
    # Remove code blocks
    content = re.sub(r'```[\s\S]*?```', '', content)
    # Remove YAML front matter
    content = re.sub(r'^---[\s\S]*?---', '', content)
    return len(content.split())


def build_outline(project_dir: str) -> dict:
    """Build complete thesis outline from chapter files."""
    project = Path(project_dir)
    phase3_dir = project / "phase-3"

    if not phase3_dir.is_dir():
        return {"error": "phase-3 directory not found", "chapters": []}

    chapters = []
    total_words = 0
    total_sections = 0

    # Find all chapter files in order
    found_files = []
    for md_file in sorted(phase3_dir.glob("*.md")):
        if md_file.name.endswith(".ko.md"):
            continue
        found_files.append(md_file)

    # Sort by CHAPTER_ORDER priority, then alphabetically
    def sort_key(f):
        name = f.name
        if name in CHAPTER_ORDER:
            return (0, CHAPTER_ORDER.index(name))
        return (1, name)

    found_files.sort(key=sort_key)

    for md_file in found_files:
        headings = extract_outline(md_file)
        words = count_words(md_file)
        total_words += words
        total_sections += len(headings)

        chapters.append({
            "file": md_file.name,
            "word_count": words,
            "sections": len(headings),
            "headings": headings,
        })

    return {
        "chapters": chapters,
        "stats": {
            "total_chapters": len(chapters),
            "total_words": total_words,
            "total_sections": total_sections,
        },
    }


def format_as_markdown(data: dict) -> str:
    """Format outline as markdown."""
    stats = data.get("stats", {})
    lines = [
        "# Thesis Outline",
        "",
        f"> {stats.get('total_chapters', 0)} files | "
        f"{stats.get('total_words', 0):,} words | "
        f"{stats.get('total_sections', 0)} sections",
        f"> Generated by generate_thesis_outline.py (P1 deterministic)",
        "",
        "---",
        "",
    ]

    for ch in data.get("chapters", []):
        lines.append(f"## {ch['file']} ({ch['word_count']:,} words)")
        lines.append("")
        for h in ch["headings"]:
            prefix = "  " * (h["level"] - 1)
            marker = "-" if h["level"] <= 2 else "·"
            lines.append(f"{prefix}{marker} {h['title']}")
        lines.append("")

    # Summary table
    lines.extend([
        "---",
        "",
        "## Chapter Summary",
        "",
        "| Chapter | Words | Sections |",
        "|---------|------:|:--------:|",
    ])
    for ch in data.get("chapters", []):
        lines.append(
            f"| {ch['file']} | {ch['word_count']:,} | {ch['sections']} |"
        )
    lines.append(
        f"| **Total** | **{stats.get('total_words', 0):,}** | "
        f"**{stats.get('total_sections', 0)}** |"
    )
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate thesis outline (P1 deterministic)"
    )
    parser.add_argument("--project-dir", required=True)
    parser.add_argument("--output", default=None)
    parser.add_argument(
        "--format", choices=["markdown", "json"], default="markdown"
    )
    args = parser.parse_args()

    data = build_outline(args.project_dir)

    if data.get("error"):
        print(f"ERROR: {data['error']}", file=sys.stderr)
        return 1

    if args.format == "json":
        output = json.dumps(data, indent=2, ensure_ascii=False)
    else:
        output = format_as_markdown(data)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Outline written to {args.output}")
        print(f"Stats: {json.dumps(data['stats'])}")
    else:
        print(output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
